version: "3.9"

services:
  api:
    build: .
    image: mac-blue-team-framework:latest
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgresql://blue:blue@postgres:5432/blue
      MINIO_ENDPOINT: http://minio:9000
      VAULT_ADDR: http://vault:8200
    depends_on:
      - postgres
      - minio
      - vault

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: blue
      POSTGRES_PASSWORD: blue
      POSTGRES_DB: blue
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  minio:
    image: minio/minio:RELEASE.2024-04-18T19-09-19Z
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address :9001
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data

  vault:
    image: hashicorp/vault:1.15
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: dev-token
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    ports:
      - "8200:8200"
    command: vault server -dev -dev-root-token-id=dev-token -dev-listen-address=0.0.0.0:8200

volumes:
  postgres-data:
  minio-data:
