name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Poetry
        run: pip install poetry==1.8.2
      - name: Install dependencies
        run: |
          poetry install --no-root
      - name: Lint
        run: |
          poetry run ruff check
      - name: Unit tests
        run: |
          poetry run pytest
